### PR TITLE
fix: remove temporary fix

### PR DESCRIPTION
**Pull request by iamar7**
### Release required?

- [ ] No release
- [x] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

##### Release notes content

The issue of `min_tls_version` default value being set to 1.1 instead of 1.2 while applying `ibm_cis_domain_settings` has been addressed in the latest version of the provider code. This PR aims to removes the temporary fix and update the `ibm-cloud` provider version to `1.63`.

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Review by maheshwarishikha — APPROVED** [review]

**Comment by maheshwarishikha** [comment]
Please update the branch and add release notes.

**Comment by toddgiguere** [comment]
@iamar7 You are skipping upgrade test, I'm assuming because of the removal of the TLS version causing it to fail.

Can you please confirm that the domain settings object, and the TLS version, is the only reason for upgrade failing? You can either run the upgrade test case and capture output, or do an upgrade test manually, then post the output in a comment on this PR that the upgrade result is only one resource planned to change, and it is the one expected?

**Comment by iamar7** [comment]
> @iamar7 You are skipping upgrade test, I'm assuming because of the removal of the TLS version causing it to fail.
> 
> Can you please confirm that the domain settings object, and the TLS version, is the only reason for upgrade failing? You can either run the upgrade test case and capture output, or do an upgrade test manually, then post the output in a comment on this PR that the upgrade result is only one resource planned to change, and it is the one expected?

Closing this PR since with the latest update the upgrade test is not failing as it was failing earlier. Raised another PR ~> https://github.com/terraform-ibm-modules/terraform-ibm-cis/pull/476 not skipping upgrade test.

**Pull request closed without merging**
